### ISSUE TITLE
Stub an empty request

### ISSUE THREAD

**Issue by mattharrigan** [carvalhorr/protoc-gen-mock#20]
Is it possible to stub the following rpc with an empty request? If so how?

```
service Greeter {
	rpc Hello(Request) returns (Response) {}
}

message Request {}

message Response {
	string greeting = 1;
}
```
Thank you

**Comment by mattharrigan** [comment]
not sure how you want to implement it, but a match type of `any` would work and might be generally useful

**Comment by carvalhorr** [comment]
I need to check about your first question on the `message Request {}`. I'll do it once I get my personal laptop.

As for the `any`, I think it would be possible to implement using a similar approach I used for the error details. The tool allows you to add `any` as the error details (see [gRPC Error Model](https://cloud.google.com/apis/design/errors#error_model) for reference). For details on how to do it using `protoc-gen-mock` see [Advanced error mocking](https://github.com/carvalhorr/protoc-gen-mock/wiki/Advanced-error-mocking).

Do you think this would work?

**Comment by mattharrigan** [comment]
Not sure I followed your comment. I was suggesting adding the following [here](https://github.com/carvalhorr/protoc-gen-mock/blob/master/stub/matcher.go#L33)

```
case "any":
    return stub
```

**Comment by mattharrigan** [comment]
I hacked up a vendored version and can confirm that using `any` per the above works for me.

**Comment by carvalhorr** [comment]
Gotcha. You can get the same result by using `partial` match type with an empty `content`. Something like this:
```
    {
        "fullMethod": "/carvalhorr.greeter.Greeter/Hello",
        "request": {
            "match": "partial",
            "content": {}
        },
        "response": {
            "type": "success",
            "content": {
                "greeting": "Hi, Rodrigo!"
            }
        }
    }
```

I need to add better documentation to the project, but the `partial' match type is supposed to match only the fields included in the stub, therefore if you include an empty payload it will match any request as you intended.

I will not implement the `any` now as there are other functionalities with higher priority.

**Comment by mattharrigan** [comment]
That works. It wasn't obvious to me, but makes sense in hindsight. Documentation would help
