### ISSUE TITLE
forget to import "fmt"

### ISSUE THREAD

**Issue by vitaneyeyu** [carvalhorr/protoc-gen-mock#23]
eg:
func _MemberDataAPI_MultiUserNumbersByMobiles_MockHandler(srv interface{}, stream grpc.ServerStream) error {
	// Mock not implemented for streaming
	return fmt.Errorf("mock not implemented for streaming")
}
the generated mock.pb.go forget to import "fmt"

**Comment by carvalhorr** [comment]
Added missing import to the generated code. See https://github.com/carvalhorr/protoc-gen-mock/pull/25
